version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build phase started...
      - python -m unittest discover  # Or your actual build/test command

artifacts:
  files:
    - '**/*'
